import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'Dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'profile',
        path: '',
        title: 'Profile',
        translateKey: 'Profile',
        icon: 'profile',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'institute_profile',
                path: '/institute_profile',
                title: 'Institute Profile',
                translateKey: 'Institute Profile',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'bank_details',
                path: '/bank_details',
                title: 'Bank Details',
                translateKey: 'Bank Details',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fee_structure',
                path: '/fee_structure',
                title: 'Fee Structure',
                translateKey: 'Fee Structure',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'rules_regulations',
                path: '/rules_regulations',
                title: 'Rules & Regulations',
                translateKey: 'Rules & Regulations',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'employees',
        path: '',
        title: 'Employees',
        translateKey: 'Employees',
        icon: 'employees',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'all_employees',
                path: '/all_employees',
                title: 'All Employees',
                translateKey: 'All Employees',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'add_employees',
                path: '/add_employees',
                title: 'Add Employees',
                translateKey: 'Add Employees',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'class',
        path: '',
        title: 'Class',
        translateKey: 'Class',
        icon: 'class',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'all_classes',
                path: '/all_classes',
                title: 'All Classes',
                translateKey: 'All Classes',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'add_classes',
                path: '/add_classes',
                title: 'Add Classes',
                translateKey: 'Add Classes',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'homework',
        path: '',
        title: 'Homework',
        translateKey: 'Homework',
        icon: 'homework',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'all_homework',
                path: '/all_homework',
                title: 'All Homework',
                translateKey: 'All Homework',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'add_homework',
                path: '/add_homework',
                title: 'Add Homework',
                translateKey: 'Add Homework',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    {
        key: 'subjects',
        path: '',
        title: 'Subjects',
        translateKey: 'Subjects',
        icon: 'subjects',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'all_subjects',
                path: '/all_subjects',
                title: 'All Subjects',
                translateKey: 'All Subjects',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'add_subjects',
                path: '/add_subjects',
                title: 'Add Subjects',
                translateKey: 'Add Subjects',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'students',
        path: '',
        title: 'Students',
        translateKey: 'Students',
        icon: 'employees',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'all_students',
                path: '/all_students',
                title: 'All Students',
                translateKey: 'All Students',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'add_students',
                path: '/add_students',
                title: 'Add Students',
                translateKey: 'Add Students',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'promote_students',
                path: '/promote_students',
                title: 'Promote Students',
                translateKey: 'Promote Students',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'timetable',
        path: '',
        title: 'Time Table',
        translateKey: 'Time Table',
        icon: 'timetable',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'create_timetable',
                path: '/create_timetable',
                title: 'Create Timetable',
                translateKey: 'Create Timetable',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'view_timetables',
                path: '/view_timetables',
                title: 'View TimeTables',
                translateKey: 'View TimeTables',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ]
    },
    {
        key: 'attendance',
        path: '',
        title: 'Attendance',
        translateKey: 'Attendance',
        icon: 'attendance',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'mark_student_attendance',
                path: '/mark_student_attendance',
                title: 'Mark Student Attendance',
                translateKey: 'Mark Student Attendance',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'view_student_attendance',
                path: '/view_student_attendance',
                title: 'View Student Attendance',
                translateKey: 'View Student Attendance',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'mark_employee_attendance',
                path: '/mark_employee_attendance',
                title: 'Mark Employee Attendance',
                translateKey: 'Mark Employee Attendance',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'view_employee_attendance',
                path: '/view_employee_attendance',
                title: 'View Employee Attendance',
                translateKey: 'View Employee Attendance',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ]
    },
    {
        key: 'canteen',
        path: '',
        title: 'Canteen',
        translateKey: 'Canteen',
        icon: 'canteen',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'add_canteen',
                path: '/add_canteen',
                title: 'Add Canteen',
                translateKey: 'Add Canteen',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'view_canteen',
                path: '/view_canteen',
                title: 'View Canteen',
                translateKey: 'View Canteen',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ]
    },
    {
        key: 'studentPanel',
        path: '',
        title: 'Student Panel',
        translateKey: 'Student Panel',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'student_profile',
                path: '/student_profile',
                title: 'My Profile',
                translateKey: 'My Profile',
                icon: 'profile',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'student_timetable',
                path: '/student_timetable',
                title: 'My Timetable',
                translateKey: 'My Timetable',
                icon: 'timetable',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'student_attendance_record',
                path: '/student_attendance_record',
                title: 'My Attendance Record',
                translateKey: 'My Attendance Record',
                icon: 'attendance',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'view_canteen',
                path: '/view_canteen',
                title: 'View Canteen',
                translateKey: 'View Canteen',
                icon: 'canteen',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'teacherPanel',
        path: '',
        title: 'Teacher Panel',
        translateKey: 'Teacher Panel',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'teacher_profile',
                path: '/teacher_profile',
                title: 'My Profile',
                translateKey: 'My Profile',
                icon: 'profile',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teacher_timetable',
                path: '/teacher_timetable',
                title: 'My Timetable',
                translateKey: 'My Timetable',
                icon: 'timetable',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'teacher_attendance_record',
                path: '/teacher_attendance_record',
                title: 'My Attendance Record',
                translateKey: 'My Attendance Record',
                icon: 'attendance',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'view_canteen',
                path: '/view_canteen',
                title: 'View Canteen',
                translateKey: 'View Canteen',
                icon: 'canteen',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
